services:
  postgres:
    image: "postgres:15"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "test"
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
  app:
    image: "python:3.12"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
