site_name: Techdox Doc

nav:
  - Projeto: README.md
  - Modulo 01: 
    - Diagrama Entidade e Relacionamento (DER): ./docs/modulo_01/DER_Hora-de-Aventura.md
    - Modelo Entidade e Relacionamento (MER): ./docs/modulo_01/MER_Hora-de-Aventura.md

theme:
  name: 'material'